### ISSUE TITLE
语言版本

### ISSUE THREAD

**Issue by wxhn1225** [Sainan/warframe-kim-dialogues#1]
有简体中文版的吗

**Comment by Sainan** [comment]
Of what exactly? I could maybe add translations to the Kimulacrum.

**Comment by Sainan** [comment]
Well, I've added a language selector to the Kimulacrum. If you want translated flowcharts, you can modify and run the Dotinator yourself.

**Comment by wxhn1225** [comment]
谢谢！介意我给其他人分享这个网站吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sainan/warframe-kim-dialogues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月21日(星期六) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sainan/warframe-kim-dialogues] 语言版本 (Issue #1)





 
Well, I've added a language selector to the Kimulacrum. If you want translated flowcharts, you can modify and run the Dotinator yourself.

**Comment by Sainan** [comment]
Of course not.

**Comment by wxhn1225** [comment]
爱你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sainan/warframe-kim-dialogues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月21日(星期六) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sainan/warframe-kim-dialogues] 语言版本 (Issue #1)





 
Of course not.
